### ISSUE TITLE
Add support for `[!TIP]` and `[!CAUTION]`

### ISSUE THREAD

**Issue by j-murata** [bent10/marked-extensions#18]
- Extension Name: marked-alert
- Extension Version: 1.2.1

### Use case
https://github.com/orgs/community/discussions/16925

### Proposal
GitHub seems to have added support for rendering `[!TIP]` and `[!CAUTION]`.
It would be greatly appreciated if `marked-alert` could follow suit.

**Comment by bent10** [comment]
I've released [`marked-alert@2.0.0`](https://github.com/bent10/marked-extensions/releases/tag/marked-alert%402.0.0) to support the current spec. Feel free to explore and let me know if you have any feedback.

**Comment by j-murata** [comment]
Hi @bent10 

Hmm, I use `marked-alert` to convert pdfs with [`md-to-pdf`](https://www.npmjs.com/package/md-to-pdf), and on v2.0.1, the color of the icon and the strings to the right of it, such as `Note` and `Important`, seems to be incorrect.

But I'm sorry, I don't know which library is responsible for this problem.

**Comment by j-murata** [comment]
The problem above may be due to the outdated CSS file I am specifying as the base (I am specifying v5.4.0 which is available [here](https://cdnjs.com/libraries/github-markdown-css)).

**Comment by bent10** [comment]
For v5.4.0, you need to include the following CSS:

```css
.markdown-body .markdown-alert.markdown-alert-tip {
  border-left-color: #57ab5a;
}

.markdown-body .markdown-alert.markdown-alert-caution {
  border-left-color: #e5534b;
}

.markdown-body .markdown-alert > .markdown-alert-title {
  display: inline-flex;
  align-items: center;
  font-weight: 500;
}

.markdown-alert-note > .markdown-alert-title {
  color: #539bf5;
}

.markdown-alert-tip > .markdown-alert-title {
  color: #57ab5a;
}

.markdown-alert-important > .markdown-alert-title {
  color: #986ee2;
}

.markdown-alert-warning > .markdown-alert-title {
  color: #c69026;
}

.markdown-alert-caution > .markdown-alert-title {
  color: #e5534b;
}

.mr-2 {
  margin-right: 0.5rem;
}
```
